# 理想汽车订单监控配置文件
# 支持定期通知功能的增强版配置

# 基础配置
order_id: "177971759268550919"          # 订单ID
check_interval: "@every 30m"            # 检查间隔

# ======================
# 新增：定期通知配置
# ======================
enable_periodic_notify: true            # 是否启用定期通知
notification_interval_hours: 24         # 定期通知间隔（小时）
always_notify_when_approaching: true    # 临近交付时是否总是通知

# 理想汽车API配置
lixiang_cookies: ""                      # 从浏览器复制的Cookie字符串

# 通知渠道配置 (至少配置一个)
serverchan_sendkey: ""                   # Server酱SendKey
serverchan_baseurl: "https://sctapi.ftqq.com/"
wechat_webhook_url: ""                   # 微信群机器人Webhook URL

# 交付预测配置
lock_order_time: "2025-09-27 13:08:00"  # 锁单时间
estimate_weeks_min: 7                   # 预计交付最少周数
estimate_weeks_max: 9                   # 预计交付最多周数

# ======================
# 配置说明
# ======================
# 1. 定期通知功能:
#    - enable_periodic_notify: 启用后即使交付时间未更新也会定期发送状态报告
#    - notification_interval_hours: 设置通知间隔，建议12-48小时
#    - always_notify_when_approaching: 临近交付时间是否强制通知
#
# 2. 通知触发条件:
#    - 交付时间有变化时立即通知
#    - 达到定期通知间隔时发送状态报告
#    - 临近交付时间时发送提醒（可配置）
#    - 初次启动时发送初始状态
#
# 3. 通知内容增强:
#    - 详细的交付状态分析
#    - 基于当前时间的进度计算
#    - 智能的状态判断和建议
#    - 倒计时和时间状态信息